"""Entry ctime

Revision ID: 163502dccb94
Revises: 16822ba2f5df
Create Date: 2019-09-17 08:41:08.724042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163502dccb94'
down_revision = '16822ba2f5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('ctime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'ctime')
    # ### end Alembic commands ###
