"""entries content and relation to log

Revision ID: 16822ba2f5df
Revises: 45b91e30dabf
Create Date: 2019-09-15 12:41:59.043962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16822ba2f5df'
down_revision = '45b91e30dabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.add_column(sa.Column('content', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('log_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('entries', 'logs', ['log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.drop_constraint('entries', type_='foreignkey')
        batch_op.drop_column('log_id')
        batch_op.drop_column('content')
    # ### end Alembic commands ###
