"""Entry mtime

Revision ID: 4edfc18a4b0a
Revises: 163502dccb94
Create Date: 2019-09-17 09:04:43.428082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edfc18a4b0a'
down_revision = '163502dccb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('mtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'mtime')
    # ### end Alembic commands ###
