"""cellphone column users

Revision ID: 65fde6c5be06
Revises: a07ff3082ff2
Create Date: 2019-09-11 16:06:09.425995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fde6c5be06'
down_revision = 'a07ff3082ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cellphone', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_cellphone'), 'users', ['cellphone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cellphone'), table_name='users')
    op.drop_column('users', 'cellphone')
    # ### end Alembic commands ###
