"""creator for entries

Revision ID: 9c74e1d40dc7
Revises: a7fec71c543c
Create Date: 2019-09-29 10:21:39.418431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c74e1d40dc7'
down_revision = 'a7fec71c543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('entries', 'logs', ['log_id'], ['id'])
        batch_op.create_foreign_key('entries', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.drop_constraint('entries', type_='foreignkey')
        batch_op.drop_constraint('entries', type_='foreignkey')
        batch_op.drop_column('creator_id')
    # ### end Alembic commands ###
