"""default READ permission for members

Revision ID: bea5ba7c81a9
Revises: 7e5ecabfc448
Create Date: 2019-09-28 23:38:26.200366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea5ba7c81a9'
down_revision = '7e5ecabfc448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.create_foreign_key('entries', 'logs', ['log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.drop_constraint('entries', type_='foreignkey')
    # ### end Alembic commands ###
