"""logs mtime & ctime

Revision ID: f9c7049c7818
Revises: 4edfc18a4b0a
Create Date: 2019-09-20 10:32:45.871268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c7049c7818'
down_revision = '4edfc18a4b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('ctime', sa.DateTime(), nullable=True))
    op.add_column('logs', sa.Column('mtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'mtime')
    op.drop_column('logs', 'ctime')
    # ### end Alembic commands ###
