"""default MembershipType READ for Memberships

Revision ID: fbc06530ccc8
Revises: 9c74e1d40dc7
Create Date: 2019-09-29 10:25:18.880057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc06530ccc8'
down_revision = '9c74e1d40dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.create_foreign_key('entries', 'logs', ['log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries") as batch_op:
        batch_op.drop_constraint('entries', type_='foreignkey')
    # ### end Alembic commands ###
